### ISSUE TITLE
Оружие переключается слишком быстро

### ISSUE THREAD

**Issue by poiNt3D** [pss88/DF#6]
Отсутствует задержка повтора клавиши при переключении оружия, в результате чего можно случайно пропустить нужное.

**Comment by binarymaster** [comment]
Увеличил задержку с 72 до 156 мс: https://github.com/pss88/DF/commit/0546dd33f2ffa4c1e052d19e553052f50b2eead2

Требуется проверка.

**Comment by cher-nov** [comment]
Проверил, теперь отлично. Можешь закрывать.
Также было бы неплохо отписать вот в этой теме комментарием-ответом:
http://doom2d.org/forum/viewtopic.php?f=12&t=1700#p29776
Тем не менее, тема не посвящена конкретно этой проблеме, поэтому галку ей ставить пока не надо.

**Comment by BlackDoomer** [comment]
Проверил, теперь отлично. Можешь закрывать.
Также было бы неплохо отписать вот в этой теме комментарием-ответом:
http://doom2d.org/forum/viewtopic.php?f=12&t=1700#p29776
Тем не менее, тема не посвящена конкретно этой проблеме, поэтому галку ей ставить пока не надо.
