### ISSUE TITLE
Магическая константа "ASS"

### ISSUE THREAD

**Issue by BlackDoomer** [pss88/DF#7]
Пробежитесь поиском по, например, g_game.pas и сразу найдёте.
Зачем оно вообще нужно?

**Comment by binarymaster** [comment]
Полагаю, это "пароль по умолчанию" :)
Встречается также в g_menu.pas и g_netmsg.pas

**Comment by BlackDoomer** [comment]
Стас, а ты можешь связаться с Примусом по поводу необходимости этого и, если возможно, исправить на канонiчную пустую строку и протестить? А то ведь не дело же, код от таких вещей только засоряется.

А ещё там где-то в коде игрок называется "уеба" в комментариях, это бы тоже неплохо бы поправить.

07.02.2015, 21:52, "binarymaster" <notifications@github.com>:

**Comment by binarymaster** [comment]
Замечательно xD
Я полагаю, Примус уже получил письмо с оповещением, как и я.

**Comment by FGSFDSFGS** [comment]
Отсылка пустых строк по сети по какой-то причине не работала, но мне лень было ее править.
