### ISSUE TITLE
Сайт doom2d.org не работает

### ISSUE THREAD

**Issue by binarymaster** [pss88/DF#8]
Доменное имя не резолвится. Что случилось?

**Comment by BlackDoomer** [comment]
A-запись у домена слетела. Я написал Джа, он сказал, что будет решать. По всей видимости, это домен попросту автоматически не продлился.

09.02.2015, 22:22, "binarymaster" <notifications@github.com>:

**Comment by binarymaster** [comment]
Временное решение проблемы, прописать в hosts:
188.93.212.21	doom2d.org

**Comment by BlackDoomer** [comment]
На самом деле, всё ещё проще.
http://cp257765.cpanel.tech-logol.ru

10.02.2015, 22:35, "binarymaster" <notifications@github.com>:

**Comment by binarymaster** [comment]
http://i.imgur.com/ms7a9RP.png
Снова...

**Comment by BlackDoomer** [comment]
Подтверждаю, доступа к mpms.doom2d.org нет, видимо скоро обновятся записи DNS у моего провайдера и я увижу то же самое. Отправил смску Джа.

12.02.2015, 19:14, "binarymaster" <notifications@github.com>:
